### ISSUE TITLE
Instead of hard coded poll interval, can I pass the interval as props?

### ISSUE THREAD

**Issue by khalid3n** [cameronbourke/react-async-poll#10]
I need to to use the react-async-poll in two different places with different poll intervals. Currently, I have to write two different wrappers with different poll intervals. Can I pass the poll interval as props?

**Comment by cameronbourke** [comment]
Thanks @khalid3n for the issue! Apologies for the extremely delayed response. From memory the issue with passing the `prop interval` down through props is that the wrapping component will not have access to the value. However, I'm not actively maintaining the repo and so I'm going to close this issue due to inactivity of my part. Thanks again!
